### ISSUE TITLE
command traefik error: failed to decode configuration from flags: field not found, node: acme

### ISSUE THREAD

**Issue by zkdev** [Egregors/youtrack-docker-compose#10]
after running `docker-compose up`

**Comment by zkdev** [comment]
https://github.com/containous/traefik/issues/5135#issuecomment-523669100

**Comment by egregors** [comment]
@zkdev It looks like broken back-compatibility for new major Traefik 2.0. I believe we should wait a little bit before upgrading. I'll pin Traefik version to v1.7.18 in the compose ASAP
