### ISSUE TITLE
Fix compose: remove redundant volumes links

### ISSUE THREAD

**Issue by egregors** [Egregors/youtrack-docker-compose#3]
`./nginx/html` volume is redundant

**Comment by icevl** [comment]
Without html directory, the letsencrypt-nginx-proxy does not start

`letsencrypt-nginx-proxy-companion_1  | Error: can't access to '/usr/share/nginx/html' directory !
letsencrypt-nginx-proxy-companion_1  | Check that '/usr/share/nginx/html' directory is declared has a writable volume.
letsencrypt-nginx-proxy-companion_1  | Warning: '/usr/share/nginx/html' does not appear to be a mounted volume.
letsencrypt-nginx-proxy-companion_1  | Warning: '/usr/share/nginx/html' does not appear to be a mounted volume.
letsencrypt-nginx-proxy-companion_1  | Error: can't access to '/usr/share/nginx/html' directory !
letsencrypt-nginx-proxy-companion_1  | Check that '/usr/share/nginx/html' directory is declared has a writable volume.
letsencrypt-nginx-proxy-companion_1  | Warning: '/usr/share/nginx/html' does not appear to be a mounted volume.
letsencrypt-nginx-proxy-companion_1  | Error: can't access to '/usr/share/nginx/html' directory !
letsencrypt-nginx-proxy-companion_1  | Check that '/usr/share/nginx/html' directory is declared has a writable volume.`
