### ISSUE TITLE
Docker-compose for both youtrack and teamcity

### ISSUE THREAD

**Issue by thanhpd56** [Egregors/youtrack-docker-compose#6]
Hi,
I'm using your project to deploy youtrack to my vps. It's working great.
However, how can i deploy both Teamcity and Youtrack just by one docker-compose file with one nginx configuration? (conflicts nginx port, configuration)
If yes, can you please give the docker-compse sample?
Thanks in advance!

**Comment by egregors** [comment]
Hi, @thanhpd56 

I understand what are you want. And you're not the only one who ask about this feature. We clearly need to do this, but unfortunately, I'm extremely loaded with work right now. I'll add this feature ASAP.
