### ISSUE TITLE
Let's Encrypt can't renew certificate if there are any when container is started

### ISSUE THREAD

**Issue by perk11** [Egregors/youtrack-docker-compose#7]
If certificates already exist when container is started, nginx config is created which includes /etc/nginx/vhost.d/default-ssl but not /etc/nginx/vhost.d/default
and /etc/nginx/vhost.d/default-ssl does not contain the .well-known location necessary for renewing certificates. So let's ecnrypt tries to renew the certificate and fails. After I removed nginx folder and restarted container, this issue disappeared.

**Comment by egregors** [comment]
Thank you, for you report. Looks like it is really annoying bug.
Unfortunately I haven't enough time for fix it right now. If you know good way to resolve this issue, feel free to make Pull Request

**Comment by egregors** [comment]
@perk11 solve it by moving to `traefik` #9
